name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install


    - name: Build Signed APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore_b64: ${{ secrets.KEYSTORE_HASH }}
        keystore_password: ${{ secrets.STORE_PASSWORD }}
        key_alias: ${{ secrets.KEY_ALIAS }}
        key_password: ${{ secrets.KEYPASSWORD }}
        gradlew_dir: ./android

