name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Configure environment variables for signing
      run: |
        echo "Setting environment variables for signing..."
        echo "::set-env name=KEYSTORE_FILE::${{ secrets.KEYSTORE_HASH }}"
        echo "::set-env name=KEYSTORE_PASSWORD::${{ secrets.KEY_PASSWORD }}"
        echo "::set-env name=KEY_ALIAS::${{ secrets.KEY_ALIAS }}"
        echo "::set-env name=KEY_PASSWORD::${{ secrets.STORE_PASSWORD }}"

    - name: Build Android app with release key store
      run: |
        cd android
        ./gradlew assembleRelease \
          -PsigningConfig=release \
          -Pandroid.signingConfigs.release.storeFile=$KEYSTORE_HASH \
          -Pandroid.signingConfigs.release.storePassword=$KEY_PASSWORD \
          -Pandroid.signingConfigs.release.keyAlias=$KEY_ALIAS \
          -Pandroid.signingConfigs.release.keyPassword=$STORE_PASSWORD

